package pve

import (
	"fmt"
	"os"
	"pb2p/internal/exec"
	"strings"
)

const storageCfgPath = "/etc/pve/storage.cfg"

// EnsurePBSStorage adds the PBS storage if it doesn't already exist. It is
// idempotent: an existing storage with the same name is detected and skipped
// rather than treated as an error.
func EnsurePBSStorage(pbsName, ip, username, tokenSecret, datastoreName, fingerprint string) error {
	exists, err := storageExists(pbsName)
	if err != nil {
		return err
	}
	if exists {
		fmt.Printf("PBS storage %s already exists, skipping creation...\n", pbsName)
		return nil
	}

	_, err = exec.Run("pvesm", "add", "pbs", pbsName,
		"--server", ip,
		"--username", username,
		"--password", tokenSecret,
		"--datastore", datastoreName,
		"--fingerprint", fingerprint,
		"--encryption-key", "autogen",
	)
	return err
}

// storageExists reports whether a storage with the given name is defined in
// storage.cfg. The config is read directly rather than via `pvesm status`,
// which errors or omits entries when a storage is unreachable.
func storageExists(name string) (bool, error) {
	data, err := os.ReadFile(storageCfgPath)
	if err != nil {
		return false, fmt.Errorf("reading %s: %w", storageCfgPath, err)
	}
	return storageListed(string(data), name), nil
}

// storageListed reports whether storageCfg contains a section header
// ("<type>: <name>") for name.
func storageListed(storageCfg, name string) bool {
	for line := range strings.SplitSeq(storageCfg, "\n") {
		fields := strings.Fields(line)
		if len(fields) == 2 && strings.HasSuffix(fields[0], ":") && fields[1] == name {
			return true
		}
	}
	return false
}

// ExportEncryptionKey copies the key generated by `--encryption-key autogen`
// into the current directory and returns the path it was written to.
func ExportEncryptionKey(pbsName string) (string, error) {
	keyPath := fmt.Sprintf("/etc/pve/priv/storage/%s.enc", pbsName)

	data, err := os.ReadFile(keyPath)
	if err != nil {
		return "", fmt.Errorf("reading encryption key %s: %w", keyPath, err)
	}

	outPath := fmt.Sprintf("%s.enc", pbsName)
	if err := os.WriteFile(outPath, data, 0600); err != nil {
		return "", fmt.Errorf("writing encryption key to %s: %w", outPath, err)
	}

	return outPath, nil
}

func SetBindMount(ctid int, poolName string, datasetName string) error {
	datasetPath := fmt.Sprintf("/mnt/%s/%s", poolName, datasetName)

	lxcConfPath := fmt.Sprintf("/etc/pve/lxc/%d.conf", ctid)

	// Skip if a mount for this dataset is already configured.
	if hasBindMount(lxcConfPath, datasetPath) {
		fmt.Printf("Bind mount for %s already configured, skipping...\n", datasetPath)
		return nil
	}

	mount := fmt.Sprintf("mp0: %s,mp=%s\n", datasetPath, datasetPath)

	f, err := os.OpenFile(lxcConfPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return fmt.Errorf("opening %s: %w", lxcConfPath, err)
	}
	defer f.Close()

	if _, err := f.WriteString(mount); err != nil {
		return fmt.Errorf("writing mp0 line to %s: %w", lxcConfPath, err)
	}

	return nil
}

func downloadTemplateIfNotExists(templateStorage, template string) error {
	exists, err := templateExists(templateStorage, template)
	if err != nil {
		return err
	}
	if exists {
		return nil
	}

	// Refresh the appliance index so pveam knows about current templates
	if _, err := exec.Run("pveam", "update"); err != nil {
		return fmt.Errorf("updating pveam index: %w", err)
	}

	if _, err := exec.Run("pveam", "download", templateStorage, template); err != nil {
		return fmt.Errorf("downloading template %s: %w", template, err)
	}

	return nil
}

func hasBindMount(lxcConfPath, datasetPath string) bool {
	data, err := os.ReadFile(lxcConfPath)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), fmt.Sprintf("mp=%s", datasetPath))
}
